src/main/java/ploting_server/ploting/core/documentation/config/SwaggerConfig.java
src/main/resources/application.yml

해결된 이슈: #1
- SwaggerConfig 설정했습니다.
- application.yml에 Swagger 설정

feat: Swagger 설정 #1

---

src/main/java/ploting_server/ploting/core/code/error/JwtErrorCode.java
src/main/java/ploting_server/ploting/core/code/error/MemberErrorCode.java
src/main/java/ploting_server/ploting/core/exception/GlobalExceptionHandler.java
src/main/java/ploting_server/ploting/core/exception/JwtException.java
src/main/java/ploting_server/ploting/core/exception/MemberException.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/core/security/filter/JwtFilter.java
src/main/java/ploting_server/ploting/core/security/principal/PrincipalDetails.java
src/main/java/ploting_server/ploting/core/security/principal/PrincipalDetailsService.java
src/main/java/ploting_server/ploting/core/security/service/jwt/JwtService.java
src/main/java/ploting_server/ploting/member/dto/server/MemberJwtDto.java
src/main/java/ploting_server/ploting/member/entity/Member.java
src/main/java/ploting_server/ploting/member/entity/ProviderType.java
src/main/java/ploting_server/ploting/member/entity/RolesType.java
src/main/java/ploting_server/ploting/member/repository/MemberRepository.java

해결된 이슈: #2 
- SecurityConfig 설정
- UserDetails 및 UserDetailsService 인터페이스 구현
- 예외 처리
- JwtFilter, JwtService 구현

feat: Spring Security 및 JWT 인증 기능 구현 #2

---

src/main/java/ploting_server/ploting/comment/entity/Comment.java
src/main/java/ploting_server/ploting/comment/entity/CommentLike.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/core/security/principal/PrincipalDetails.java
src/main/java/ploting_server/ploting/core/security/service/jwt/JwtService.java
src/main/java/ploting_server/ploting/core/security/service/oauth/KakaoOAuthService.java
src/main/java/ploting_server/ploting/core/security/service/oauth/NaverOAuthService.java
src/main/java/ploting_server/ploting/meeting/entity/Meeting.java
src/main/java/ploting_server/ploting/meeting/entity/MeetingLike.java
src/main/java/ploting_server/ploting/meeting/entity/MeetingMember.java
src/main/java/ploting_server/ploting/member/dto/request/OAuthAuthorizationRequest.java
src/main/java/ploting_server/ploting/member/dto/request/OAuthLoginRequest.java
src/main/java/ploting_server/ploting/member/dto/server/MemberJwtDto.java
src/main/java/ploting_server/ploting/member/dto/server/MemberLoginDto.java
src/main/java/ploting_server/ploting/member/entity/GenderType.java
src/main/java/ploting_server/ploting/member/entity/Member.java
src/main/java/ploting_server/ploting/member/entity/RoleType.java
src/main/java/ploting_server/ploting/member/repository/MemberRepository.java
src/main/java/ploting_server/ploting/member/service/AuthService.java
src/main/java/ploting_server/ploting/mission/entity/Mission.java
src/main/java/ploting_server/ploting/mission/entity/Point.java
src/main/java/ploting_server/ploting/organization/entity/Organization.java
src/main/java/ploting_server/ploting/organization/entity/OrganizationLike.java
src/main/java/ploting_server/ploting/organization/entity/OrganizationMember.java
src/main/java/ploting_server/ploting/post/entity/Post.java
src/main/java/ploting_server/ploting/post/entity/PostLike.java
src/main/java/ploting_server/ploting/post/entity/PostType.java
src/main/resources/application.yml

해결된 이슈: #8 
- ERD 바탕으로 Entity 세팅

feat: ERD 바탕으로 Entity 세팅 #8

---

src/main/java/ploting_server/ploting/comment/entity/Comment.java
src/main/java/ploting_server/ploting/comment/repository/CommentRepository.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/core/security/service/oauth/KakaoOAuthService.java
src/main/java/ploting_server/ploting/core/security/service/oauth/NaverOAuthService.java
src/main/java/ploting_server/ploting/core/security/service/oauth/OAuthService.java
src/main/java/ploting_server/ploting/meeting/entity/Meeting.java
src/main/java/ploting_server/ploting/member/controller/AuthController.java
src/main/java/ploting_server/ploting/member/controller/MemberController.java
src/main/java/ploting_server/ploting/member/dto/request/MemberRegisterRequest.java
src/main/java/ploting_server/ploting/member/dto/request/MemberUpdateRequest.java
src/main/java/ploting_server/ploting/member/dto/response/MemberInfoResponse.java
src/main/java/ploting_server/ploting/member/dto/response/MemberNicknameDuplicationResponse.java
src/main/java/ploting_server/ploting/member/dto/server/MemberOAuthLoginDto.java
src/main/java/ploting_server/ploting/member/entity/Member.java
src/main/java/ploting_server/ploting/member/repository/MemberRepository.java
src/main/java/ploting_server/ploting/member/service/AuthService.java
src/main/java/ploting_server/ploting/member/service/MemberService.java
src/main/java/ploting_server/ploting/post/entity/Post.java
src/main/java/ploting_server/ploting/post/repository/PostRepository.java

해결된 이슈: #12
- 회원 등록하기
- 프로필 조회하기
- 닉네임 중복 여부
- 프로필 수정
- 회원 탈퇴하기

feat: 회원 CRUD API 개발 #12

---

.github/workflows/deploy.yaml
.gitignore
Dockerfile

해결된 이슈: None
> AWS를 통해 배포를 자동화하는 github actions workflow를 추가하였습니다.
> gradle 빌드 스크립트 확인 부탁드립니다.

ci: github actions를 통한 배포 스크립트 추가 ( WIP )

---

src/main/java/ploting_server/ploting/core/code/error/OrganizationErrorCode.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/organization/controller/OrganizationController.java
src/main/java/ploting_server/ploting/organization/entity/OrganizationMember.java
src/main/java/ploting_server/ploting/organization/repository/OrganizationMemberRepository.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java

해결된 이슈: #11
- 단체장 권한 위임 API 추가
- 단체의 멤버 강퇴 API 추가

feat: 단체 단체장 API 개발 #11

---

src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java

fix: CORS Origin 수정 #24

---

src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java

fix: CORS Origin 수정 2 #26

---

src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/organization/controller/OrganizationController.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java

해결된 이슈: #10
- 단체 가입 API 추가
- 단체 탈퇴 API 추가

feat: 단체 멤버 API 개발 #10

---

src/main/java/ploting_server/ploting/core/code/error/OrganizationErrorCode.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/member/dto/request/MemberUpdateRequest.java
src/main/java/ploting_server/ploting/member/entity/Member.java
src/main/java/ploting_server/ploting/member/service/AuthService.java
src/main/java/ploting_server/ploting/organization/entity/Organization.java
src/main/java/ploting_server/ploting/organization/entity/OrganizationMember.java
src/main/java/ploting_server/ploting/organization/repository/OrganizationMemberRepository.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java

해결된 이슈: #29
- 회원 가입 시 level 초기 1로 설정
- 회원 수정 생년월일도 가능하게 처리
- 단체 관련 비즈니스 로직 예외 처리
- 필터체인 엔드포인트 /(슬래쉬) 누락 처리

fix: 단체 API 버그 처리 #29

---

src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java

fix: CORS 임시 개방 #32

---

src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java

fix: CORS Origin 수정 #35

---

src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java

해결된 이슈: #40
SecurityConfig Preflight 설정 추가

fix: SecurityConfig Preflight 설정 추가 #40

---

src/main/java/ploting_server/ploting/core/security/filter/JwtFilter.java

해결된 이슈: #42
OPTIONS 메서드 필터 안 거치게 설정

fix: OPTIONS 메서드 필터 안 거치게 설정 #42

---

src/main/java/ploting_server/ploting/comment/entity/Comment.java
src/main/java/ploting_server/ploting/core/code/error/OrganizationErrorCode.java
src/main/java/ploting_server/ploting/member/entity/Member.java
src/main/java/ploting_server/ploting/member/service/MemberService.java
src/main/java/ploting_server/ploting/organization/entity/Organization.java
src/main/java/ploting_server/ploting/organization/repository/OrganizationLikeRepository.java
src/main/java/ploting_server/ploting/organization/repository/OrganizationMemberRepository.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java
src/main/java/ploting_server/ploting/post/entity/Post.java

해결된 이슈: #57
회원 탈퇴, 단체 삭제 로직 수정

fix: 회원 탈퇴, 단체 삭제 로직 수정 #57

---

src/main/java/ploting_server/ploting/organization/controller/OrganizationController.java
src/main/java/ploting_server/ploting/organization/controller/OrganizationLeaderController.java
src/main/java/ploting_server/ploting/organization/service/OrganizationLeaderService.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java

해결된 이슈: #59
단체장 API, 단체 공통 API 분리

refactor: 단체장 API, 단체 공통 API 분리 #59

---

src/main/java/ploting_server/ploting/core/exception/CustomSecurityException.java
src/main/java/ploting_server/ploting/core/exception/GlobalExceptionHandler.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/core/security/handler/CustomAccessDeniedHandler.java

해결된 이슈: #61
AccessDeniedHandler 추가

feat: AccessDeniedHandler 추가 #61

---

src/main/java/ploting_server/ploting/core/code/error/MeetingErrorCode.java
src/main/java/ploting_server/ploting/core/exception/GlobalExceptionHandler.java
src/main/java/ploting_server/ploting/core/exception/MeetingException.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/meeting/controller/MeetingLeaderController.java
src/main/java/ploting_server/ploting/meeting/dto/request/MeetingCreateRequest.java
src/main/java/ploting_server/ploting/meeting/dto/request/MeetingUpdateRequest.java
src/main/java/ploting_server/ploting/meeting/entity/Meeting.java
src/main/java/ploting_server/ploting/meeting/entity/MeetingMember.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingLikeRepository.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingMemberRepository.java
src/main/java/ploting_server/ploting/meeting/service/MeetingLeaderService.java
src/main/java/ploting_server/ploting/organization/controller/OrganizationLeaderController.java
src/main/java/ploting_server/ploting/organization/service/OrganizationLeaderService.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java

해결된 이슈: #45
모임장 API 개발
아직 개발 중입니다.

feat: 모임장 API 개발 #45

---

src/main/java/ploting_server/ploting/core/code/error/MeetingErrorCode.java
src/main/java/ploting_server/ploting/core/code/error/OrganizationErrorCode.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/meeting/controller/MeetingController.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingInfoResponse.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingListResponse.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingMemberListResponse.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingMemberResponse.java
src/main/java/ploting_server/ploting/meeting/entity/MeetingMember.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingLikeRepository.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingMemberRepository.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingRepository.java
src/main/java/ploting_server/ploting/meeting/service/MeetingLeaderService.java
src/main/java/ploting_server/ploting/meeting/service/MeetingService.java
src/main/java/ploting_server/ploting/organization/controller/OrganizationController.java
src/main/java/ploting_server/ploting/organization/dto/response/OrganizationMemberResponse.java
src/main/java/ploting_server/ploting/organization/service/OrganizationLeaderService.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java

해결된 이슈: #46
모임 API 개발
아직 개발 중입니다.

feat: 모임 API 개발 #46

---

src/main/java/ploting_server/ploting/core/code/error/MeetingErrorCode.java
src/main/java/ploting_server/ploting/core/code/error/MemberErrorCode.java
src/main/java/ploting_server/ploting/core/code/error/OrganizationErrorCode.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/meeting/controller/MeetingLikeController.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingLikeRepository.java
src/main/java/ploting_server/ploting/meeting/service/MeetingLikeService.java
src/main/java/ploting_server/ploting/member/service/MemberService.java
src/main/java/ploting_server/ploting/organization/service/OrganizationLikeService.java

feat: 모임 좋아요 API 개발 #47

---

src/main/java/ploting_server/ploting/PlotingApplication.java
src/main/java/ploting_server/ploting/meeting/entity/Meeting.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingRepository.java
src/main/java/ploting_server/ploting/meeting/service/MeetingLeaderService.java
src/main/java/ploting_server/ploting/meeting/service/MeetingScheduler.java

해결된 이슈: #65
종료된 모임 비활성화 스케줄러 추가

feat: 종료된 모임 비활성화 스케줄러 추가 #65

---

src/main/java/ploting_server/ploting/PlotingApplication.java
src/main/java/ploting_server/ploting/comment/dto/response/CommentListResponse.java
src/main/java/ploting_server/ploting/comment/entity/Comment.java
src/main/java/ploting_server/ploting/core/code/error/JwtErrorCode.java
src/main/java/ploting_server/ploting/core/code/error/MemberErrorCode.java
src/main/java/ploting_server/ploting/core/code/error/OAuthErrorCode.java
src/main/java/ploting_server/ploting/core/code/error/OrganizationErrorCode.java
src/main/java/ploting_server/ploting/core/code/error/PostErrorCode.java
src/main/java/ploting_server/ploting/core/exception/GlobalExceptionHandler.java
src/main/java/ploting_server/ploting/core/exception/PostException.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/member/entity/Member.java
src/main/java/ploting_server/ploting/organization/service/OrganizationLeaderService.java
src/main/java/ploting_server/ploting/post/controller/PostController.java
src/main/java/ploting_server/ploting/post/dto/request/PostCreateRequest.java
src/main/java/ploting_server/ploting/post/dto/request/PostUpdateRequest.java
src/main/java/ploting_server/ploting/post/dto/response/PostInfoResponse.java
src/main/java/ploting_server/ploting/post/entity/Post.java
src/main/java/ploting_server/ploting/post/entity/PostType.java
src/main/java/ploting_server/ploting/post/repository/PostLikeRepository.java
src/main/java/ploting_server/ploting/post/service/PostService.java

feat: 게시글 CRUD API 개발 #49

---

src/main/java/ploting_server/ploting/comment/controller/CommentController.java
src/main/java/ploting_server/ploting/comment/dto/request/CommentCreateRequest.java
src/main/java/ploting_server/ploting/comment/dto/request/CommentUpdateRequest.java
src/main/java/ploting_server/ploting/comment/entity/Comment.java
src/main/java/ploting_server/ploting/comment/repository/CommentLikeRepository.java
src/main/java/ploting_server/ploting/comment/service/CommentService.java
src/main/java/ploting_server/ploting/core/code/error/CommentErrorCode.java
src/main/java/ploting_server/ploting/core/exception/CommentException.java
src/main/java/ploting_server/ploting/core/exception/GlobalExceptionHandler.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/meeting/entity/Meeting.java
src/main/java/ploting_server/ploting/meeting/service/MeetingLeaderService.java
src/main/java/ploting_server/ploting/meeting/service/MeetingService.java
src/main/java/ploting_server/ploting/organization/entity/Organization.java
src/main/java/ploting_server/ploting/organization/service/OrganizationLeaderService.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java
src/main/java/ploting_server/ploting/post/entity/Post.java
src/main/java/ploting_server/ploting/post/service/PostService.java

feat: 댓글 CUD API 개발 #52

---

src/main/java/ploting_server/ploting/core/code/error/PostErrorCode.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/post/controller/PostLikeController.java
src/main/java/ploting_server/ploting/post/entity/Post.java
src/main/java/ploting_server/ploting/post/repository/PostLikeRepository.java
src/main/java/ploting_server/ploting/post/service/PostLikeService.java

feat: 게시글 좋아요 API 개발 #53

---

src/main/java/ploting_server/ploting/comment/controller/CommentLikeController.java
src/main/java/ploting_server/ploting/comment/dto/response/CommentListResponse.java
src/main/java/ploting_server/ploting/comment/entity/Comment.java
src/main/java/ploting_server/ploting/comment/repository/CommentLikeRepository.java
src/main/java/ploting_server/ploting/comment/service/CommentLikeService.java
src/main/java/ploting_server/ploting/core/code/error/CommentErrorCode.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/post/service/PostService.java

feat: 댓글 좋아요 API 개발 #51

---

src/main/java/ploting_server/ploting/core/code/error/PostErrorCode.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/main/controller/MainController.java
src/main/java/ploting_server/ploting/main/dto/response/FilteredResponse.java
src/main/java/ploting_server/ploting/main/entity/FilterType.java
src/main/java/ploting_server/ploting/main/service/MainService.java
src/main/java/ploting_server/ploting/meeting/dto/request/MeetingCreateRequest.java
src/main/java/ploting_server/ploting/meeting/dto/request/MeetingUpdateRequest.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingInfoResponse.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingListResponse.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingRepository.java
src/main/java/ploting_server/ploting/meeting/service/MeetingService.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java
src/main/java/ploting_server/ploting/post/dto/response/PostListResponse.java
src/main/java/ploting_server/ploting/post/repository/PostRepository.java
src/main/resources/application.yml

해결된 이슈: #48
모든 게시글과 모임 조회 및 검색 API 개발

feat: 모든 게시글과 모임 조회 및 검색 API 개발 #48

---

src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingRepository.java
src/main/java/ploting_server/ploting/post/controller/PostController.java
src/main/java/ploting_server/ploting/post/repository/PostRepository.java
src/main/java/ploting_server/ploting/post/service/PostService.java

feat: 게시글 목록 조회 API 개발 #50

---

src/main/java/ploting_server/ploting/comment/dto/response/CommentInfoResponse.java
src/main/java/ploting_server/ploting/comment/entity/Comment.java
src/main/java/ploting_server/ploting/main/dto/response/FilteredResponse.java
src/main/java/ploting_server/ploting/main/service/MainService.java
src/main/java/ploting_server/ploting/meeting/controller/MeetingLeaderController.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingInfoResponse.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingMemberResponse.java
src/main/java/ploting_server/ploting/meeting/entity/Meeting.java
src/main/java/ploting_server/ploting/meeting/service/MeetingService.java
src/main/java/ploting_server/ploting/member/dto/response/MemberNicknameDuplicationResponse.java
src/main/java/ploting_server/ploting/member/service/MemberService.java
src/main/java/ploting_server/ploting/organization/dto/response/OrganizationInfoResponse.java
src/main/java/ploting_server/ploting/organization/dto/response/OrganizationMemberResponse.java
src/main/java/ploting_server/ploting/organization/entity/Organization.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java
src/main/java/ploting_server/ploting/post/dto/response/PostInfoResponse.java
src/main/java/ploting_server/ploting/post/service/PostService.java
src/main/java/ploting_server/ploting/utils/controller/UtilsController.java

해결된 이슈: #71 
단체, 모임, 게시글, 댓글 본인 여부 응답으로 보내기

feat: 단체, 모임, 게시글, 댓글 본인 여부 응답으로 보내기 #71

---

src/main/java/ploting_server/ploting/core/code/error/MissionErrorCode.java
src/main/java/ploting_server/ploting/core/exception/GlobalExceptionHandler.java
src/main/java/ploting_server/ploting/core/exception/MissionException.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/core/security/dto/jwt/request/RefreshTokenRequest.java
src/main/java/ploting_server/ploting/core/security/dto/jwt/response/JwtTokenResponse.java
src/main/java/ploting_server/ploting/core/security/handler/CustomAccessDeniedHandler.java
src/main/java/ploting_server/ploting/core/security/service/jwt/JwtService.java
src/main/java/ploting_server/ploting/core/security/service/oauth/CustomOAuth2SuccessHandler.java
src/main/java/ploting_server/ploting/member/controller/AuthController.java
src/main/java/ploting_server/ploting/member/service/AuthService.java
src/main/java/ploting_server/ploting/mission/controller/MissionController.java
src/main/java/ploting_server/ploting/mission/dto/request/MissionCreateRequest.java
src/main/java/ploting_server/ploting/mission/dto/response/MissionInfoResponse.java
src/main/java/ploting_server/ploting/mission/dto/response/MissionListResponse.java
src/main/java/ploting_server/ploting/mission/repository/MissionRepository.java
src/main/java/ploting_server/ploting/mission/service/MissionService.java
src/main/java/ploting_server/ploting/point/entity/Point.java

feat: 미션 CRD API 개발 #79

---

src/main/java/ploting_server/ploting/core/code/error/PointErrorCode.java
src/main/java/ploting_server/ploting/core/exception/GlobalExceptionHandler.java
src/main/java/ploting_server/ploting/core/exception/PointException.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/filter/service/FilterService.java
src/main/java/ploting_server/ploting/point/controller/PointController.java
src/main/java/ploting_server/ploting/point/dto/response/PointInfoResponse.java
src/main/java/ploting_server/ploting/point/dto/response/PointListResponse.java
src/main/java/ploting_server/ploting/point/entity/LevelType.java
src/main/java/ploting_server/ploting/point/repository/PointRepository.java
src/main/java/ploting_server/ploting/point/service/PointService.java

feat: 포인트 CR API 개발 #80

---

src/main/java/ploting_server/ploting/filter/controller/FilterController.java
src/main/java/ploting_server/ploting/mission/controller/MissionController.java

docs: Swagger 응답 문서 수정 #85

---

src/main/java/ploting_server/ploting/comment/dto/response/CommentInfoResponse.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingMemberListResponse.java
src/main/java/ploting_server/ploting/meeting/service/MeetingService.java
src/main/java/ploting_server/ploting/member/dto/request/MemberUpdateRequest.java
src/main/java/ploting_server/ploting/member/dto/response/MemberInfoResponse.java
src/main/java/ploting_server/ploting/member/entity/Member.java
src/main/java/ploting_server/ploting/member/service/MemberService.java
src/main/java/ploting_server/ploting/organization/dto/response/OrganizationInfoResponse.java
src/main/java/ploting_server/ploting/organization/dto/response/OrganizationMemberListResponse.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java
src/main/java/ploting_server/ploting/point/controller/PointController.java
src/main/java/ploting_server/ploting/post/dto/response/PostInfoResponse.java
src/main/java/ploting_server/ploting/post/service/PostService.java

해결된 이슈: #86 
레벨에 따라 레벨명 응답에 추가

feat: 레벨에 따라 레벨명 응답에 추가 #86

---

src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/meeting/controller/MeetingLeaderController.java
src/main/java/ploting_server/ploting/organization/controller/OrganizationLeaderController.java

해결된 이슈: #94 
MVP 아닌 API 스웨거에서 안 보이게 처리 (강퇴, 권한 위임)

docs: MVP 아닌 API 스웨거에서 안 보이게 처리 #94

---

src/main/java/ploting_server/ploting/comment/repository/CommentLikeRepository.java
src/main/java/ploting_server/ploting/comment/repository/CommentRepository.java
src/main/java/ploting_server/ploting/core/code/error/JwtErrorCode.java
src/main/java/ploting_server/ploting/core/code/error/MeetingErrorCode.java
src/main/java/ploting_server/ploting/core/code/error/OrganizationErrorCode.java
src/main/java/ploting_server/ploting/core/security/filter/JwtFilter.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingMemberRepository.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingRepository.java
src/main/java/ploting_server/ploting/member/controller/MemberController.java
src/main/java/ploting_server/ploting/member/service/MemberService.java
src/main/java/ploting_server/ploting/organization/service/OrganizationLeaderService.java
src/main/java/ploting_server/ploting/point/repository/PointRepository.java

feat: 회원 삭제 로직 수정 #87

---

src/main/java/ploting_server/ploting/meeting/repository/MeetingRepository.java
src/main/java/ploting_server/ploting/organization/service/OrganizationLeaderService.java

feat: 단체 삭제 로직 수정 #88

---

src/main/java/ploting_server/ploting/meeting/service/MeetingLeaderService.java

feat: 모임 삭제 로직 수정 #93

---

src/main/java/ploting_server/ploting/filter/service/FilterService.java
src/main/java/ploting_server/ploting/meeting/controller/MeetingController.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingInfoResponse.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingListResponse.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingRepository.java
src/main/java/ploting_server/ploting/meeting/service/MeetingService.java
src/main/java/ploting_server/ploting/organization/dto/response/OrganizationInfoResponse.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java

해결된 이슈: #95 
- 모든 모임 목록 조회 API 개발
- 단체 세부 정보 조회 로직 수정

feat: 모든 모임 목록 조회 API 개발 및 단체 세부 정보 조회 로직 수정 #95

---

src/main/java/ploting_server/ploting/comment/controller/CommentController.java
src/main/java/ploting_server/ploting/comment/controller/CommentLikeController.java
src/main/java/ploting_server/ploting/core/response/BfResponse.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/filter/controller/FilterController.java
src/main/java/ploting_server/ploting/meeting/controller/MeetingController.java
src/main/java/ploting_server/ploting/meeting/controller/MeetingLeaderController.java
src/main/java/ploting_server/ploting/meeting/controller/MeetingLikeController.java
src/main/java/ploting_server/ploting/member/controller/AuthController.java
src/main/java/ploting_server/ploting/member/controller/MemberController.java
src/main/java/ploting_server/ploting/member/dto/response/MemberInfoResponse.java
src/main/java/ploting_server/ploting/member/entity/Member.java
src/main/java/ploting_server/ploting/member/service/MemberService.java
src/main/java/ploting_server/ploting/mission/controller/MissionController.java
src/main/java/ploting_server/ploting/organization/controller/OrganizationController.java
src/main/java/ploting_server/ploting/organization/controller/OrganizationLeaderController.java
src/main/java/ploting_server/ploting/organization/controller/OrganizationLikeController.java
src/main/java/ploting_server/ploting/point/controller/PointController.java
src/main/java/ploting_server/ploting/point/repository/PointRepository.java
src/main/java/ploting_server/ploting/point/service/PointService.java
src/main/java/ploting_server/ploting/post/controller/PostController.java
src/main/java/ploting_server/ploting/post/controller/PostLikeController.java

feat: 포인트에 따라 회원 레벨 반영 #91

---

src/main/java/ploting_server/ploting/core/security/service/oauth/CustomOAuth2SuccessHandler.java

해결된 이슈: #103 
OAuth 토큰 URL 방식으로 수정

feat: OAuth 토큰 URL 방식으로 수정 #103

---

src/main/java/ploting_server/ploting/post/dto/response/PostInfoResponse.java
src/main/java/ploting_server/ploting/post/service/PostService.java

해결된 이슈: #111
게시글 정보 조회 시 생성시간 포함

feat: 게시글 정보 조회 시 생성시간 포함 #111

---

src/main/java/ploting_server/ploting/comment/dto/response/CommentListResponse.java
src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/member/controller/MemberController.java
src/main/java/ploting_server/ploting/post/dto/response/PostInfoResponse.java
src/main/java/ploting_server/ploting/post/service/PostService.java

해결된 이슈: #114
프론트 API 부착 중 발생하는 비즈니스 에러 해결

fix: 프론트 API 부착 중 발생하는 비즈니스 에러 해결 #114

---

src/main/java/ploting_server/ploting/filter/controller/FilterController.java
src/main/java/ploting_server/ploting/filter/service/FilterService.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingInfoResponse.java
src/main/java/ploting_server/ploting/meeting/dto/response/MeetingListResponse.java
src/main/java/ploting_server/ploting/meeting/service/MeetingService.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java
src/main/java/ploting_server/ploting/post/dto/response/PostInfoResponse.java
src/main/java/ploting_server/ploting/post/dto/response/PostListResponse.java
src/main/java/ploting_server/ploting/post/service/PostService.java

feat: 응답 생성시간 가공 #113

---

src/main/java/ploting_server/ploting/core/code/error/PointErrorCode.java
src/main/java/ploting_server/ploting/member/dto/response/MemberInfoResponse.java
src/main/java/ploting_server/ploting/member/service/MemberService.java
src/main/java/ploting_server/ploting/point/dto/response/PointListResponse.java
src/main/java/ploting_server/ploting/point/entity/GrassType.java
src/main/java/ploting_server/ploting/point/entity/LevelType.java
src/main/java/ploting_server/ploting/point/service/PointService.java

해결된 이슈: #117 
- 잔디 응답 수정
- 회원 정보 조회 API 회원 ID 추가

feat: 잔디 응답 수정 #117

---

src/main/java/ploting_server/ploting/core/security/config/SecurityConfig.java
src/main/java/ploting_server/ploting/meeting/controller/MeetingController.java
src/main/java/ploting_server/ploting/meeting/repository/MeetingRepository.java
src/main/java/ploting_server/ploting/meeting/service/MeetingService.java
src/main/java/ploting_server/ploting/organization/dto/response/OrganizationInfoResponse.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java

해결된 이슈: #120
단체의 최신 모임 하나 조회 수정 및 단체의 모임 목록 조회 API 개발

feat:   Issues list  단체의 최신 모임 하나 조회 수정 및 단체의 모임 목록 조회 API 개발 #120

---

src/main/java/ploting_server/ploting/meeting/dto/response/MeetingInfoResponse.java
src/main/java/ploting_server/ploting/meeting/service/MeetingService.java

해결된 이슈: #122 
모임 세부 정보 조회 API에 단체 Id 추가

feat: 모임 세부 정보 조회 API에 단체 Id 추가 #122

---

src/main/java/ploting_server/ploting/core/code/error/MeetingErrorCode.java
src/main/java/ploting_server/ploting/core/code/error/OrganizationErrorCode.java
src/main/java/ploting_server/ploting/meeting/controller/MeetingController.java
src/main/java/ploting_server/ploting/meeting/controller/MeetingLeaderController.java
src/main/java/ploting_server/ploting/meeting/service/MeetingLeaderService.java
src/main/java/ploting_server/ploting/meeting/service/MeetingService.java
src/main/java/ploting_server/ploting/organization/controller/OrganizationController.java
src/main/java/ploting_server/ploting/organization/controller/OrganizationLeaderController.java
src/main/java/ploting_server/ploting/organization/service/OrganizationLeaderService.java
src/main/java/ploting_server/ploting/organization/service/OrganizationService.java

feat: 단체, 모임 조건 제약 걸기 #119

---

src/main/java/ploting_server/ploting/meeting/repository/MeetingRepository.java
src/main/java/ploting_server/ploting/meeting/service/MeetingService.java

해결된 이슈: #126 
단체의 모임 조회 모임 날짜로 정렬
단체의 모임 조회 모임 날짜로 정렬

feat: 단체의 모임 조회 모임 날짜로 정렬 #126
